//
// Post.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Post: JSONEncodable {
    public var id: Int32?
    public var body: String?
    public var handle: String?
    public var emotes: [EmoteTotals]?
    public var infractions: [InfractionTotals]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["body"] = self.body
        nillableDictionary["handle"] = self.handle
        nillableDictionary["emotes"] = self.emotes?.encodeToJSON()
        nillableDictionary["infractions"] = self.infractions?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
