//
// RoomsAndEmotes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class RoomsAndEmotes: JSONEncodable {
    public var rooms: [Room]?
    public var emotes: [Emote]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["rooms"] = self.rooms?.encodeToJSON()
        nillableDictionary["emotes"] = self.emotes?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
